version: '3.8' # Specify the

services:
  db:
    image: mysql:8 # MySQL version
    container_name: mysqljava
    environment:
      MYSQL_ROOT_PASSWORD: admin123   # Root password
      MYSQL_DATABASE: ecommercedb             # Database name
      MYSQL_USER: root                    # Non-root user
      MYSQL_PASSWORD: admin123        # Password for the non-root user
    ports:
      - "3307:3306"
#    volumes:
#      - ab2ac9c5a8b25c9e3cd6df5bab9430fb86e2e5da5cc91581f63656b06565bcb5:/var/lib/mysql
#    networks:
#      - bridge
#
#networks:
#  my_network:
#    driver: bridge