app:
    redis:
        enabled: true
    frontend:
        url: ${FE_URL:https://e-commerce-shop-fe.onrender.com}

aws:
    access_key: ${AWS_ACCESS_KEY}
    region: ${AWS_REGION}
    s3:
        bucket:
            name: ${AWS_S3_BUCKET_NAME}
    secret_key: ${AWS_SECRET_KEY}

jwt:
    expiration-ms: 900000
    refresh-expiration-ms: 604800000
    secret: ${JWT_SECRET_KEY}

rate-limit:
    trusted-proxies:
        - 127.0.0.1
        - 0:0:0:0:0:0:0:1
        - ::1
        - 10.0.0.5
#        - 192.168.1.32    // local ip address for dev to avoid rate limit
    default-rule:
        max-requests: 10
        time-unit: MINUTES
        time-window: 1
    rules:
        api:
            max-requests: 50
            time-unit: MINUTES
            time-window: 1
        forgotPassword:
            max-requests: 5
            time-unit: MINUTES
            time-window: 1
        login:
            max-requests: 5
            time-unit: MINUTES
            time-window: 1
        refresh:
            max-requests: 5
            time-unit: MINUTES
            time-window: 1
        register:
            max-requests: 3
            time-unit: MINUTES
            time-window: 1
        resetPassword:
            max-requests: 3
            time-unit: MINUTES
            time-window: 1

server:
    port: 8888

spring:
    application:
        name: Ecommerce
    cache:
        ttl:
            category-all: 600
            category-by-name: 300
            default: 300
            home-products: 300
            product-by-alias: 600
        type: redis
    config:
        import: optional:file:.env[.properties]
    data:
        redis:
            host: ${REDIS_HOST:localhost}
            lettuce:
                pool:
                    max-active: 8
                    max-idle: 4
                    min-idle: 1
                    max-wait: 2000ms
            password: ${REDIS_PASSWORD:}
            port: ${REDIS_PORT:6379}
            ssl:
                enabled: true
            timeout: 15000ms
            url: ${REDIS_URL:}
            username: ${REDIS_USERNAME:}
    datasource:
        driver-class-name: org.postgresql.Driver
        hikari:
            connectionTimeout: 30000
            idleTimeout: 600000
            maximumPoolSize: 10
        password: ${DB_PASSWORD}
        url: ${DB_URL}
        username: ${DB_USER}
    devtools:
        livereload:
            enabled: false
    http:
        multipart:
            enabled: true
            max-file-size: 10MB
            max-request-size: 10MB
    jpa:
        hibernate:
            ddl-auto: validate
        open-in-view: false
        properties:
            hibernate:
                format_sql: true
        show-sql: false
    main:
        banner-mode: 'off'
    security:
        oauth2:
            client:
                registration:
                    facebook:
                        client-id: ${FACEBOOK_CLIENT_ID}
                        client-secret: ${FACEBOOK_CLIENT_SECRET}
                        scope: email, public-profile
                    google:
                        client-id: ${GOOGLE_CLIENT_ID}
                        client-secret: ${GOOGLE_CLIENT_SECRET}
                        scope: email, profile
    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB
