aws:
    access_key: ${AWS_ACCESS_KEY}
    region: ${AWS_REGION}
    s3:
        bucket:
            name: ${AWS_S3_BUCKET_NAME}
    secret_key: ${AWS_SECRET_KEY}
jwt:
    secretKey: ${JWT_SECRET_KEY}
logging:
    level:
        com:
            shopping: debug
        root: error
server:
    port: 8888
spring:
    application:
        name: Ecommerce
    devtools:
        livereload:
            enabled: false
    config:
        import: optional:file:.env[.properties]
    datasource:
        driver-class-name: org.postgresql.Driver
        url: ${DB_URL}
        username: ${DB_USER}
        password: ${DB_PASSWORD}
        hikari:
            maximumPoolSize: 10
            connectionTimeout: 30000
            idleTimeout: 600000
    http:
        multipart:
            enabled: true
            max-file-size: 10MB
            max-request-size: 10MB
    jpa:
        hibernate:
            ddl-auto: update
        properties:
            hibernate:
                format_sql: true
        show-sql: false
        open-in-view: false
    main:
        banner-mode: 'off'
    security:
        oauth2:
            client:
                registration:
                    google:
                        client-id: ${GOOGLE_CLIENT_ID}
                        client-secret: ${GOOGLE_CLIENT_SECRET}
                        scope: email, profile
                    facebook:
                        client-id: ${FACEBOOK_CLIENT_ID}
                        client-secret: ${FACEBOOK_CLIENT_SECRET}
                        scope: email, public-profile

    servlet:
        multipart:
            max-file-size: 10MB
            max-request-size: 10MB
